server:
  port: 8080
  servlet:
    context-path: /test/idea
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  cache:
    redis:
      time-to-live: 5M
  redis:
    port: 6379
    host: 127.0.0.1
    password: 123456
    timeout: 10000ms
hbase:
  config:
    hbase.zookeeper.quorum: 192.168.99.100
    hbase.zookeeper.port: 2181
    hbase.zookeeper.znode: /hbase
    hbase.client.keyvalue.maxsize: 1572864000

